name = "GeniePackageManager"
uuid = "3bdcc7f3-4b7d-42a1-be8e-724ecf5e3574"
authors = ["Abhi... <8083613+AbhimanyuAryan@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
