name = "GeniePackageManager"
uuid = "3bdcc7f3-4b7d-42a1-be8e-724ecf5e3574"
authors = ["Genie Framework Team // genieframework.com"]
version = "1.0.1"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
Genie = "5"
Pkg = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
